apiVersion: v1
kind: Pod
metadata:
  name: python-microservice
  namespace: tech.prod
spec:
  containers:
    - name: python-microservice-container
      image: your-docker-repo/python-microservice:latest
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "3Gi"
      env:
        - name: ENVIRONMENT
          value: "production"
  network:
    name: internal-prod
